name: Dijital_Panel_Guncelleyici

on:
  workflow_dispatch: # Manuel çalıştırma düğmesi

jobs:
  islem_yap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kutuphaneyi Yukle
        run: pip install requests

      - name: Verileri Isle
        run: python process.py

      - name: Sonuclari Kaydet
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add result.json
          git commit -m "Otomatik veri guncellemesi" || exit 0
          git push
