name: Python Calistir
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python data_process.py
    - run: |
        git config --global user.name 'Robot'
        git config --global user.email 'robot@github.com'
        git add results.json
        git commit -m "Guncellendi" || exit 0
        git push
